server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            - Path=/student/**
            - Path=/teacher/**
        - id: ANALYTICS-SERVICE
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/class/**
            - Path=/department/**
            - Path=/subject/**
        - id: FEEDBACK-SERVICE
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost